#!/usr/bin/env python
# Tssah just SSH easy connector utility
#

import sys
import os
import re
import subprocess

from os.path import expanduser

HOME = os.path.join(expanduser("~"), ".tssah")
USER = os.environ.get("TSSAH_USER", "")
if len(USER.strip()) == 0:
    USER = os.environ["USER"]
SERVERS = []

def ensure_home():
    if not os.path.isdir(HOME):
        os.makedirs(HOME)

def show_usage():
    global SERVERS
    cmd_name = sys.argv[0]
    s = cmd_name.split("/")
    if len(s) > 1:
        cmd_name = s[-1]
    print("")
    print("")
    print("")
    print("USAGE:")
    print("        $ %s [SERVER-NAME]" % cmd_name)
    print("")
    print("Example:")
    print("        $ %s alpha1" % cmd_name)
    print("")
    print("To listing all registered servers and it data, just run it with param `--ls`, eg:\n")
    print("        $ %s --ls" % cmd_name)
    print("")
    print("REGISTERED SERVERS:\n")
    _server_names = map(lambda a: a["name"], SERVERS)
    print_sorted_list(_server_names, columns=3, ljust=20)
    print("\n")


def print_sorted_list(data, rows=0, columns=0, ljust=10):
    """
    Prints sorted item of the list data structure formated using
    the rows and columns parameters
    This function taken from: https://stackoverflow.com/a/33464001
    """

    if not data:
        return

    if rows:
        # column-wise sorting
        # we must know the number of rows to print on each column
        # before we print the next column. But since we cannot
        # move the cursor backwards (unless using ncurses library)
        # we have to know what each row with look like upfront
        # so we are basically printing the rows line by line instead
        # of printing column by column
        lines = {}
        for count, item in enumerate(sorted(data)):
            lines.setdefault(count % rows, []).append(item)
        for key, value in sorted(lines.items()):
            for item in value:
                print item.ljust(ljust),
            print
    elif columns:
        # row-wise sorting
        # we just need to know how many columns should a row have
        # before we print the next row on the next line.
        for count, item in enumerate(sorted(data), 1):
            print item.ljust(ljust),
            if count % columns == 0:
                print
    else:
        print sorted(data)  # the default print behaviour

def read_server_file(server_file):
    def to_js(a):
        if len(a) == 4:
            return {"name": a[0], "host": a[1], "port": a[2], "user_name": a[3]}
        else:
            return {"name": a[0], "host": a[1], "port": a[2], "user_name": ""}
     
    server_list = []
    with open(server_file, "r") as f:
        _servers = f.readlines()
        _servers = filter(lambda a: not a.startswith("#"), _servers)
        _servers = map(lambda a: a.strip(), _servers)
        _servers = filter(lambda x: len(x) > 5, _servers)
        _servers_s = map(lambda a: re.split("\\s+", a), _servers)
        server_list = map(to_js, _servers_s)
    
    return server_list

def main():
    global SERVERS
    ensure_home()

    SERVER_TXT = os.path.join(HOME, "servers.txt")

    # check for existance
    # install automatically if the binary file not found
    BIN = "/usr/local/bin/tssah"
    if not os.path.exists(BIN):
        print("Installing...")
        
        sudo_cmd = ""
        if not os.access(os.path.dirname(BIN), os.W_OK | os. X_OK):
            print("Need write permission to install tssah. Sudo command is needed...")
            sudo_cmd = "sudo " 

        os.system(sudo_cmd + "wget https://raw.githubusercontent.com/anvie/tssah/master/tssah -O " + BIN)
        os.system(sudo_cmd + "chmod +x " + BIN)
        print("Done.")

    if os.path.exists(SERVER_TXT):
        SERVERS = read_server_file(SERVER_TXT)        
    else:
        with open(SERVER_TXT, "w") as f:
            f.write("# Add your servers here\n")
            f.write("# Using this format: [NAME] [IP-OR-HOST-NAME] [PORT] [USER]\n")
            f.write("# Eg:\n")
            f.write("# alpha1 123.11.22.33 771 root\n")

    if len(sys.argv) < 2:
        show_usage()
        return 2

    if sys.argv[1].startswith("--"):
        print("\nSERVERS:\n")
        if sys.argv[1] == "--ls":
            for sv in SERVERS:
                user_name = USER
                if len(sv["user_name"]) > 0:
                    user_name = sv["user_name"]
                print("  - %s host=%s port=%s user=%s" % (sv["name"], sv["host"], sv["port"], user_name))
        print("")
        return 0

    name = sys.argv[1]

    try:
        sv = (a for a in SERVERS if a["name"].lower() == name.lower()).next()
        print("Connecting %s..." % sv["name"])

        _user = USER
        if len(sv["user_name"].strip()) > 0:
            _user = sv["user_name"]

        target = "%s@%s" % (_user, sv["host"])
        print("target: " + target)
        os.system("ssh %s -p %s" % (target, sv["port"]))

    except StopIteration:
        print("No server with name %s" % name)
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main())
